### ISSUE TITLE
Size by inner child

### ISSUE THREAD

**Issue by olegys** [RitickSaha/glassmorphism#12]
Greetings!
Can you please tell me how can I make the size of the container to the size of the inner child?

**Comment by RitickSaha** [comment]
Hi, @olegys 

So in order to make the parent widget take the size of the child you will need to make use of `GlassmorphicFlexContainer` .. 
And make sure that your child widgets ar also responsive.

You can see this in action in the bottom link from line 170.

https://github.com/RitickSaha/glassmorphism/blob/master/example/lib/main.dart#L170

**Comment by olegys** [comment]
Hi, @RitickSaha 
Thanks for the quick response !

**Comment by ajaygosh102** [comment]
`GlassmorphicFlexContainer` does not depend on the child.  how can I make the size of the container to the size of the inner child?

**Comment by RitickSaha** [comment]
> `GlassmorphicFlexContainer` does not depend on the child. how can I make the size of the container to the size of the inner child?

Can you share your simplified snippet?
So that I could suggest some changes.

**Comment by olegys** [comment]
@RitickSaha Hi!
Perhaps @ajaygosh102 meant such a decision.  When for example the container in the list takes the dimensions of the child.

![IMG_20211125_205725](https://user-images.githubusercontent.com/18525409/143490838-373237cd-7137-410c-8f40-5ba3ec436db4.jpg)

**Comment by RitickSaha** [comment]
@olegys This is created with `GlassmorphicFlexContainer` widget  right?

**Comment by olegys** [comment]
> @olegys This is created with `GlassmorphicFlexContainer` widget right?

@RitickSaha Unfortunately no. I tried to use your plugin but I couldn't get it to work like this.  I am using regular BackDropFilter.
