### ISSUE TITLE
Unable to pub get the package. 

### ISSUE THREAD

**Issue by raul215** [RitickSaha/glassmorphism#3]
The error I get is given below:

Error on line 30, column 3 of pubspec.yaml: A package may not list itself as a dependency.

**Comment by RitickSaha** [comment]
> The error I get is given below:
> 
> Error on line 30, column 3 of pubspec.yaml: A package may not list itself as a dependency.

Let me check if something has occurred this error!

**Comment by RitickSaha** [comment]
![image](https://user-images.githubusercontent.com/42250993/114384659-a3387b00-9bac-11eb-9a0b-9a71bc01a04f.png)

Works fine on my side check it, If you are missing something from your side.
Or to be more clear send a code snippet or Steps to recreate the problem.
@raul215

**Comment by RitickSaha** [comment]
Closed this issue because of no further updates and legit information regarding the issue.

**Comment by raul215** [comment]
Hi

I am sorry. I will get to you soon.

**Comment by RitickSaha** [comment]
No worries buddy, You can re-open the issue whenever you want.
