### ISSUE TITLE
null-safety support

### ISSUE THREAD

**Issue by woogi-kang** [RitickSaha/glassmorphism#4]
Hello do you have any plans for making this library null-safety?

**Comment by RitickSaha** [comment]
You will get the Null safe version within this week..
I will get to it soon!

**Comment by RitickSaha** [comment]
@woogi-kang Thank you  💕 for your request to add the support of null safety to Glassmorphism.
I am happy ☺ to inform you that, the Null safer version is now live and released for use. 
You can use the null safe version by the simple steps mentioned below.

<h3>Depend on it</h3>
<p>Run this command:</p>
<p>With Flutter:</p>
  $ flutter pub add glassmorphism
 <h3>Or</h3>
dependencies: <br>
<p>glassmorphism: ^2.0.1</p>
Reference :
[Installing  Help](https://pub.dev/packages/glassmorphism/install)

**Comment by woogi-kang** [comment]
Thank you so much for fast response! We will let you know once we migrate our design to glassmorphism!
