### ISSUE TITLE
Make the height and width dynamically adjust with the content

### ISSUE THREAD

**Issue by pratikbaid3** [RitickSaha/glassmorphism#6]
Currently, the height and width is a mandatory parameter which provides some constraints in terms of the responsiveness of the widget. Would it be possible to make these fit dynamically to the content within like the standard container does?

**Comment by C0RALINA** [comment]
Yes, you can use the following properties:

final screenWidth = MediaQuery.of(context).size.width;
final screenHeight = MediaQuery.of(context).size.height;


then:


width: screenWidth - 20,
height: screenHeight - 245,

or

width: screenWidth / 2,
height: screenHeight *0.9,

**Comment by RitickSaha** [comment]
> Hi, I haven't figured out a way to do exactly that, but I use the following to change the container size dynamically based on the screen size:
> 
> final screenWidth = MediaQuery.of(context).size.width;
> final screenHeight = MediaQuery.of(context).size.height;
> 
> then:
> 
> width: screenWidth - 20,
> height: screenHeight - 245,
> 
> or
> 
> width: screenWidth / 2,
> height: screenHeight *0.9,

That’s s a great way to make your design response according to Device sizes. Because there is the use of custom painter in the package the widget requires a pre-defined size to render the canvas according to the size.

To Make the HIght and Width adjust dynamically you can use these widget:

- Flexible
- Expanded
- FittedBox

or you can use MediaQuery to understand the device size as @C0RALINA explains.

**Comment by princeteck** [comment]
> 
> 
> > Hi, I haven't figured out a way to do exactly that, but I use the following to change the container size dynamically based on the screen size:
> > final screenWidth = MediaQuery.of(context).size.width;
> > final screenHeight = MediaQuery.of(context).size.height;
> > then:
> > width: screenWidth - 20,
> > height: screenHeight - 245,
> > or
> > width: screenWidth / 2,
> > height: screenHeight *0.9,
> 
> That’s s a great way to make your design response according to Device sizes. Because there is the use of custom painter in the package the widget requires a pre-defined size to render the canvas according to the size.
> 
> To Make the HIght and Width adjust dynamically you can use these widgets:
> 
>     * Flexible [GUIDE](https://api.flutter.dev/flutter/widgets/Flexible-class.html)
> 
>     * Expanded [GUIDE](https://api.flutter.dev/flutter/widgets/Expanded-class.html)
> 
>     * FittedBox [GUIDE](https://api.flutter.dev/flutter/widgets/FittedBox-class.html)
> 
> 
> or you can use [MediaQuery](https://api.flutter.dev/flutter/widgets/MediaQuery-class.html) to understand the device size as @C0RALINA explains.

You have made the option  as required due to which if we are not using those properties, we atleast needs to assign `null` value which doesn't make any sense.

**Comment by RitickSaha** [comment]
closes #7 
You can now upgrade to `glassmorphism: ^3.0.0` and use GlassmorphismFlexContainer to do this stuff easily.
