### ISSUE TITLE
Glassmorphism effect doesnt work over googlemap on iOS

### ISSUE THREAD

**Issue by C0RALINA** [RitickSaha/glassmorphism#7]
Hi there,

Im developing an app using Flutter for both iOS and Android devices.

When the user taps on a marker on the map (GoogleMap) a Diologbox opens and displays the GlassmorphicContainer over the GoogleMap background, in turn displaying some text.

The effect works great on Android, but on iOS for some reason, the blurry glassmorphic effect only happens over widgets such as custom buttons, etc, but doesnt blur out the actual googlemap, text or markers on the googlemap. On Android, everything within the GlassmorphicContainer is blurred out perfectly.

Any ideas?

**Comment by RitickSaha** [comment]
Hi, @C0RALINA,
Can you provide some more information like:
- Package used for GoogleMaps
- Screenshot or glimpse of what went wrong
- Code Snippet

These will help me understand that what exactly the problem is. Making a wild guess by my understanding till now is that, GoogleMaps View can be a web view embedded into flutter and there can be a bug in flutter SDK with Ios specifically.

**Comment by C0RALINA** [comment]
Hi Ritick,

Thanks for replying to the question..

I'm using the latest googleMap flutter package (google_maps_flutter: ^2.0.6).

Code is similar to your example file, but here is a screenshot so you can see the difference between Android and iOS..

![Screenshot 2021-07-31 at 11 59 01 PM](https://user-images.githubusercontent.com/70142032/127745585-999f12d6-918b-4eb7-8a7b-7e6b825ebe08.png)

Thanks for your help!

**Comment by RitickSaha** [comment]
@C0RALINA 
It seems that there are many devs who have faced this issue. Basically, this issue is because there is a bug in Flutter ios SDK related to BackDropFilter this issue can be coined as a clone for the issue link below.
https://github.com/flutter/flutter/issues/56789

**Comment by C0RALINA** [comment]
Thanks for looking into this, hopefully the bug can be resolved.

**Comment by benji-farquhar** [comment]
This now works when switching the Flutter channel to beta. Not sure where exactly the cut-off point is for the minimum version of Flutter that has this working.

**Comment by RitickSaha** [comment]
@BenjiFarquhar Thanks for your finding. I will have a look into this, Let's see if I can find something to make it work in the new release.

**Comment by benji-farquhar** [comment]
@RitickSaha You're welcome. If you mean to make this package work on a google map with beta Flutter, it already does.

**Comment by RitickSaha** [comment]
That's good enough already but we can see the problem with the stable version. I guess the JS interoperability can be an issue. Just a wild guess.

**Comment by benji-farquhar** [comment]
It was a [Flutter issue](https://github.com/flutter/flutter/issues/43902#issue-515431364), so I don't think it will be possible. It was fixed last September/October by [this](https://github.com/flutter/engine/pull/34596#issue-1301357324), and [this](https://github.com/flutter/engine/pull/34596#issue-1301357324).
